// Mock for terminal-kit to work with Jest
const mockTerminal = {
  width: 80,
  height: 24,
  clear: jest.fn(),
  moveTo: jest.fn(),
  eraseLineAfter: jest.fn(),
  eraseLine: jest.fn(),
  saveCursor: jest.fn(),
  restoreCursor: jest.fn(),
  hideCursor: jest.fn(),
  showCursor: jest.fn(),
  beep: jest.fn(),
  bell: jest.fn(),
  bold: jest.fn(),
  dim: jest.fn(),
  italic: jest.fn(),
  underline: jest.fn(),
  blink: jest.fn(),
  inverse: jest.fn(),
  reset: jest.fn(),
  brightRed: jest.fn(),
  brightGreen: jest.fn(),
  brightYellow: jest.fn(),
  brightBlue: jest.fn(),
  brightMagenta: jest.fn(),
  brightCyan: jest.fn(),
  brightWhite: jest.fn(),
  red: jest.fn(),
  green: jest.fn(),
  yellow: jest.fn(),
  blue: jest.fn(),
  magenta: jest.fn(),
  cyan: jest.fn(),
  white: jest.fn(),
  gray: jest.fn(),
  black: jest.fn(),
  bgRed: jest.fn(),
  bgGreen: jest.fn(),
  bgYellow: jest.fn(),
  bgBlue: jest.fn(),
  bgMagenta: jest.fn(),
  bgCyan: jest.fn(),
  bgWhite: jest.fn(),
  bgBlack: jest.fn(),
  on: jest.fn(),
  once: jest.fn(),
  off: jest.fn(),
  emit: jest.fn(),
  removeListener: jest.fn(),
  removeAllListeners: jest.fn(),
};

const terminalKit = {
  terminal: mockTerminal,
  createTerminal: jest.fn(() => mockTerminal),
};

module.exports = terminalKit;
module.exports.default = terminalKit;
